// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/MoveAndPassiveSkillDigit.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ReMastersLib {

  /// <summary>Holder for reflection information generated from Proto/MoveAndPassiveSkillDigit.proto</summary>
  public static partial class MoveAndPassiveSkillDigitReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/MoveAndPassiveSkillDigit.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MoveAndPassiveSkillDigitReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRQcm90by9Nb3ZlQW5kUGFzc2l2ZVNraWxsRGlnaXQucHJvdG8SDFJlTWFz",
            "dGVyc0xpYiLxAgoYTW92ZUFuZFBhc3NpdmVTa2lsbERpZ2l0EgoKAmlkGAEg",
            "ASgDEg4KBnBhcmFtMRgCIAEoAxIOCgZwYXJhbTIYAyABKAMSDgoGcGFyYW0z",
            "GAQgASgDEg4KBnBhcmFtNBgFIAEoAxIOCgZwYXJhbTUYBiABKAMSDgoGcGFy",
            "YW02GAcgASgDEg4KBnBhcmFtNxgIIAEoAxIOCgZwYXJhbTgYCSABKAMSDgoG",
            "cGFyYW05GAogASgDEg8KB3BhcmFtMTAYCyABKAMSDwoHcGFyYW0xMRgMIAEo",
            "AxIPCgdwYXJhbTEyGA0gASgDEg8KB3BhcmFtMTMYDiABKAMSDwoHcGFyYW0x",
            "NBgPIAEoAxIPCgdwYXJhbTE1GBAgASgDEg8KB3BhcmFtMTYYESABKAMSDwoH",
            "cGFyYW0xNxgSIAEoAxIPCgdwYXJhbTE4GBMgASgDEg8KB3BhcmFtMTkYFCAB",
            "KAMSDwoHcGFyYW0yMBgVIAEoAyJYCh1Nb3ZlQW5kUGFzc2l2ZVNraWxsRGln",
            "aXRUYWJsZRI3CgdlbnRyaWVzGAEgAygLMiYuUmVNYXN0ZXJzTGliLk1vdmVB",
            "bmRQYXNzaXZlU2tpbGxEaWdpdGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.MoveAndPassiveSkillDigit), global::ReMastersLib.MoveAndPassiveSkillDigit.Parser, new[]{ "Id", "Param1", "Param2", "Param3", "Param4", "Param5", "Param6", "Param7", "Param8", "Param9", "Param10", "Param11", "Param12", "Param13", "Param14", "Param15", "Param16", "Param17", "Param18", "Param19", "Param20" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.MoveAndPassiveSkillDigitTable), global::ReMastersLib.MoveAndPassiveSkillDigitTable.Parser, new[]{ "Entries" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class MoveAndPassiveSkillDigit : pb::IMessage<MoveAndPassiveSkillDigit>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MoveAndPassiveSkillDigit> _parser = new pb::MessageParser<MoveAndPassiveSkillDigit>(() => new MoveAndPassiveSkillDigit());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MoveAndPassiveSkillDigit> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.MoveAndPassiveSkillDigitReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveAndPassiveSkillDigit() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveAndPassiveSkillDigit(MoveAndPassiveSkillDigit other) : this() {
      id_ = other.id_;
      param1_ = other.param1_;
      param2_ = other.param2_;
      param3_ = other.param3_;
      param4_ = other.param4_;
      param5_ = other.param5_;
      param6_ = other.param6_;
      param7_ = other.param7_;
      param8_ = other.param8_;
      param9_ = other.param9_;
      param10_ = other.param10_;
      param11_ = other.param11_;
      param12_ = other.param12_;
      param13_ = other.param13_;
      param14_ = other.param14_;
      param15_ = other.param15_;
      param16_ = other.param16_;
      param17_ = other.param17_;
      param18_ = other.param18_;
      param19_ = other.param19_;
      param20_ = other.param20_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveAndPassiveSkillDigit Clone() {
      return new MoveAndPassiveSkillDigit(this);
    }

    /// <summary>Field number for the "id" field.</summary>
    public const int IdFieldNumber = 1;
    private long id_;
    /// <summary>
    /// Move id or Passive id
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Id {
      get { return id_; }
      set {
        id_ = value;
      }
    }

    /// <summary>Field number for the "param1" field.</summary>
    public const int Param1FieldNumber = 2;
    private long param1_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param1 {
      get { return param1_; }
      set {
        param1_ = value;
      }
    }

    /// <summary>Field number for the "param2" field.</summary>
    public const int Param2FieldNumber = 3;
    private long param2_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param2 {
      get { return param2_; }
      set {
        param2_ = value;
      }
    }

    /// <summary>Field number for the "param3" field.</summary>
    public const int Param3FieldNumber = 4;
    private long param3_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param3 {
      get { return param3_; }
      set {
        param3_ = value;
      }
    }

    /// <summary>Field number for the "param4" field.</summary>
    public const int Param4FieldNumber = 5;
    private long param4_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param4 {
      get { return param4_; }
      set {
        param4_ = value;
      }
    }

    /// <summary>Field number for the "param5" field.</summary>
    public const int Param5FieldNumber = 6;
    private long param5_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param5 {
      get { return param5_; }
      set {
        param5_ = value;
      }
    }

    /// <summary>Field number for the "param6" field.</summary>
    public const int Param6FieldNumber = 7;
    private long param6_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param6 {
      get { return param6_; }
      set {
        param6_ = value;
      }
    }

    /// <summary>Field number for the "param7" field.</summary>
    public const int Param7FieldNumber = 8;
    private long param7_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param7 {
      get { return param7_; }
      set {
        param7_ = value;
      }
    }

    /// <summary>Field number for the "param8" field.</summary>
    public const int Param8FieldNumber = 9;
    private long param8_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param8 {
      get { return param8_; }
      set {
        param8_ = value;
      }
    }

    /// <summary>Field number for the "param9" field.</summary>
    public const int Param9FieldNumber = 10;
    private long param9_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param9 {
      get { return param9_; }
      set {
        param9_ = value;
      }
    }

    /// <summary>Field number for the "param10" field.</summary>
    public const int Param10FieldNumber = 11;
    private long param10_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param10 {
      get { return param10_; }
      set {
        param10_ = value;
      }
    }

    /// <summary>Field number for the "param11" field.</summary>
    public const int Param11FieldNumber = 12;
    private long param11_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param11 {
      get { return param11_; }
      set {
        param11_ = value;
      }
    }

    /// <summary>Field number for the "param12" field.</summary>
    public const int Param12FieldNumber = 13;
    private long param12_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param12 {
      get { return param12_; }
      set {
        param12_ = value;
      }
    }

    /// <summary>Field number for the "param13" field.</summary>
    public const int Param13FieldNumber = 14;
    private long param13_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param13 {
      get { return param13_; }
      set {
        param13_ = value;
      }
    }

    /// <summary>Field number for the "param14" field.</summary>
    public const int Param14FieldNumber = 15;
    private long param14_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param14 {
      get { return param14_; }
      set {
        param14_ = value;
      }
    }

    /// <summary>Field number for the "param15" field.</summary>
    public const int Param15FieldNumber = 16;
    private long param15_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param15 {
      get { return param15_; }
      set {
        param15_ = value;
      }
    }

    /// <summary>Field number for the "param16" field.</summary>
    public const int Param16FieldNumber = 17;
    private long param16_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param16 {
      get { return param16_; }
      set {
        param16_ = value;
      }
    }

    /// <summary>Field number for the "param17" field.</summary>
    public const int Param17FieldNumber = 18;
    private long param17_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param17 {
      get { return param17_; }
      set {
        param17_ = value;
      }
    }

    /// <summary>Field number for the "param18" field.</summary>
    public const int Param18FieldNumber = 19;
    private long param18_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param18 {
      get { return param18_; }
      set {
        param18_ = value;
      }
    }

    /// <summary>Field number for the "param19" field.</summary>
    public const int Param19FieldNumber = 20;
    private long param19_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param19 {
      get { return param19_; }
      set {
        param19_ = value;
      }
    }

    /// <summary>Field number for the "param20" field.</summary>
    public const int Param20FieldNumber = 21;
    private long param20_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Param20 {
      get { return param20_; }
      set {
        param20_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MoveAndPassiveSkillDigit);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MoveAndPassiveSkillDigit other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Id != other.Id) return false;
      if (Param1 != other.Param1) return false;
      if (Param2 != other.Param2) return false;
      if (Param3 != other.Param3) return false;
      if (Param4 != other.Param4) return false;
      if (Param5 != other.Param5) return false;
      if (Param6 != other.Param6) return false;
      if (Param7 != other.Param7) return false;
      if (Param8 != other.Param8) return false;
      if (Param9 != other.Param9) return false;
      if (Param10 != other.Param10) return false;
      if (Param11 != other.Param11) return false;
      if (Param12 != other.Param12) return false;
      if (Param13 != other.Param13) return false;
      if (Param14 != other.Param14) return false;
      if (Param15 != other.Param15) return false;
      if (Param16 != other.Param16) return false;
      if (Param17 != other.Param17) return false;
      if (Param18 != other.Param18) return false;
      if (Param19 != other.Param19) return false;
      if (Param20 != other.Param20) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Id != 0L) hash ^= Id.GetHashCode();
      if (Param1 != 0L) hash ^= Param1.GetHashCode();
      if (Param2 != 0L) hash ^= Param2.GetHashCode();
      if (Param3 != 0L) hash ^= Param3.GetHashCode();
      if (Param4 != 0L) hash ^= Param4.GetHashCode();
      if (Param5 != 0L) hash ^= Param5.GetHashCode();
      if (Param6 != 0L) hash ^= Param6.GetHashCode();
      if (Param7 != 0L) hash ^= Param7.GetHashCode();
      if (Param8 != 0L) hash ^= Param8.GetHashCode();
      if (Param9 != 0L) hash ^= Param9.GetHashCode();
      if (Param10 != 0L) hash ^= Param10.GetHashCode();
      if (Param11 != 0L) hash ^= Param11.GetHashCode();
      if (Param12 != 0L) hash ^= Param12.GetHashCode();
      if (Param13 != 0L) hash ^= Param13.GetHashCode();
      if (Param14 != 0L) hash ^= Param14.GetHashCode();
      if (Param15 != 0L) hash ^= Param15.GetHashCode();
      if (Param16 != 0L) hash ^= Param16.GetHashCode();
      if (Param17 != 0L) hash ^= Param17.GetHashCode();
      if (Param18 != 0L) hash ^= Param18.GetHashCode();
      if (Param19 != 0L) hash ^= Param19.GetHashCode();
      if (Param20 != 0L) hash ^= Param20.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Param1 != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Param1);
      }
      if (Param2 != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Param2);
      }
      if (Param3 != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Param3);
      }
      if (Param4 != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Param4);
      }
      if (Param5 != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Param5);
      }
      if (Param6 != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(Param6);
      }
      if (Param7 != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(Param7);
      }
      if (Param8 != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(Param8);
      }
      if (Param9 != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(Param9);
      }
      if (Param10 != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(Param10);
      }
      if (Param11 != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(Param11);
      }
      if (Param12 != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(Param12);
      }
      if (Param13 != 0L) {
        output.WriteRawTag(112);
        output.WriteInt64(Param13);
      }
      if (Param14 != 0L) {
        output.WriteRawTag(120);
        output.WriteInt64(Param14);
      }
      if (Param15 != 0L) {
        output.WriteRawTag(128, 1);
        output.WriteInt64(Param15);
      }
      if (Param16 != 0L) {
        output.WriteRawTag(136, 1);
        output.WriteInt64(Param16);
      }
      if (Param17 != 0L) {
        output.WriteRawTag(144, 1);
        output.WriteInt64(Param17);
      }
      if (Param18 != 0L) {
        output.WriteRawTag(152, 1);
        output.WriteInt64(Param18);
      }
      if (Param19 != 0L) {
        output.WriteRawTag(160, 1);
        output.WriteInt64(Param19);
      }
      if (Param20 != 0L) {
        output.WriteRawTag(168, 1);
        output.WriteInt64(Param20);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Id != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(Id);
      }
      if (Param1 != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Param1);
      }
      if (Param2 != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(Param2);
      }
      if (Param3 != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Param3);
      }
      if (Param4 != 0L) {
        output.WriteRawTag(40);
        output.WriteInt64(Param4);
      }
      if (Param5 != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Param5);
      }
      if (Param6 != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(Param6);
      }
      if (Param7 != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(Param7);
      }
      if (Param8 != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(Param8);
      }
      if (Param9 != 0L) {
        output.WriteRawTag(80);
        output.WriteInt64(Param9);
      }
      if (Param10 != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(Param10);
      }
      if (Param11 != 0L) {
        output.WriteRawTag(96);
        output.WriteInt64(Param11);
      }
      if (Param12 != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(Param12);
      }
      if (Param13 != 0L) {
        output.WriteRawTag(112);
        output.WriteInt64(Param13);
      }
      if (Param14 != 0L) {
        output.WriteRawTag(120);
        output.WriteInt64(Param14);
      }
      if (Param15 != 0L) {
        output.WriteRawTag(128, 1);
        output.WriteInt64(Param15);
      }
      if (Param16 != 0L) {
        output.WriteRawTag(136, 1);
        output.WriteInt64(Param16);
      }
      if (Param17 != 0L) {
        output.WriteRawTag(144, 1);
        output.WriteInt64(Param17);
      }
      if (Param18 != 0L) {
        output.WriteRawTag(152, 1);
        output.WriteInt64(Param18);
      }
      if (Param19 != 0L) {
        output.WriteRawTag(160, 1);
        output.WriteInt64(Param19);
      }
      if (Param20 != 0L) {
        output.WriteRawTag(168, 1);
        output.WriteInt64(Param20);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Id != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Id);
      }
      if (Param1 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Param1);
      }
      if (Param2 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Param2);
      }
      if (Param3 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Param3);
      }
      if (Param4 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Param4);
      }
      if (Param5 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Param5);
      }
      if (Param6 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Param6);
      }
      if (Param7 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Param7);
      }
      if (Param8 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Param8);
      }
      if (Param9 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Param9);
      }
      if (Param10 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Param10);
      }
      if (Param11 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Param11);
      }
      if (Param12 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Param12);
      }
      if (Param13 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Param13);
      }
      if (Param14 != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Param14);
      }
      if (Param15 != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Param15);
      }
      if (Param16 != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Param16);
      }
      if (Param17 != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Param17);
      }
      if (Param18 != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Param18);
      }
      if (Param19 != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Param19);
      }
      if (Param20 != 0L) {
        size += 2 + pb::CodedOutputStream.ComputeInt64Size(Param20);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MoveAndPassiveSkillDigit other) {
      if (other == null) {
        return;
      }
      if (other.Id != 0L) {
        Id = other.Id;
      }
      if (other.Param1 != 0L) {
        Param1 = other.Param1;
      }
      if (other.Param2 != 0L) {
        Param2 = other.Param2;
      }
      if (other.Param3 != 0L) {
        Param3 = other.Param3;
      }
      if (other.Param4 != 0L) {
        Param4 = other.Param4;
      }
      if (other.Param5 != 0L) {
        Param5 = other.Param5;
      }
      if (other.Param6 != 0L) {
        Param6 = other.Param6;
      }
      if (other.Param7 != 0L) {
        Param7 = other.Param7;
      }
      if (other.Param8 != 0L) {
        Param8 = other.Param8;
      }
      if (other.Param9 != 0L) {
        Param9 = other.Param9;
      }
      if (other.Param10 != 0L) {
        Param10 = other.Param10;
      }
      if (other.Param11 != 0L) {
        Param11 = other.Param11;
      }
      if (other.Param12 != 0L) {
        Param12 = other.Param12;
      }
      if (other.Param13 != 0L) {
        Param13 = other.Param13;
      }
      if (other.Param14 != 0L) {
        Param14 = other.Param14;
      }
      if (other.Param15 != 0L) {
        Param15 = other.Param15;
      }
      if (other.Param16 != 0L) {
        Param16 = other.Param16;
      }
      if (other.Param17 != 0L) {
        Param17 = other.Param17;
      }
      if (other.Param18 != 0L) {
        Param18 = other.Param18;
      }
      if (other.Param19 != 0L) {
        Param19 = other.Param19;
      }
      if (other.Param20 != 0L) {
        Param20 = other.Param20;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            Param1 = input.ReadInt64();
            break;
          }
          case 24: {
            Param2 = input.ReadInt64();
            break;
          }
          case 32: {
            Param3 = input.ReadInt64();
            break;
          }
          case 40: {
            Param4 = input.ReadInt64();
            break;
          }
          case 48: {
            Param5 = input.ReadInt64();
            break;
          }
          case 56: {
            Param6 = input.ReadInt64();
            break;
          }
          case 64: {
            Param7 = input.ReadInt64();
            break;
          }
          case 72: {
            Param8 = input.ReadInt64();
            break;
          }
          case 80: {
            Param9 = input.ReadInt64();
            break;
          }
          case 88: {
            Param10 = input.ReadInt64();
            break;
          }
          case 96: {
            Param11 = input.ReadInt64();
            break;
          }
          case 104: {
            Param12 = input.ReadInt64();
            break;
          }
          case 112: {
            Param13 = input.ReadInt64();
            break;
          }
          case 120: {
            Param14 = input.ReadInt64();
            break;
          }
          case 128: {
            Param15 = input.ReadInt64();
            break;
          }
          case 136: {
            Param16 = input.ReadInt64();
            break;
          }
          case 144: {
            Param17 = input.ReadInt64();
            break;
          }
          case 152: {
            Param18 = input.ReadInt64();
            break;
          }
          case 160: {
            Param19 = input.ReadInt64();
            break;
          }
          case 168: {
            Param20 = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Id = input.ReadInt64();
            break;
          }
          case 16: {
            Param1 = input.ReadInt64();
            break;
          }
          case 24: {
            Param2 = input.ReadInt64();
            break;
          }
          case 32: {
            Param3 = input.ReadInt64();
            break;
          }
          case 40: {
            Param4 = input.ReadInt64();
            break;
          }
          case 48: {
            Param5 = input.ReadInt64();
            break;
          }
          case 56: {
            Param6 = input.ReadInt64();
            break;
          }
          case 64: {
            Param7 = input.ReadInt64();
            break;
          }
          case 72: {
            Param8 = input.ReadInt64();
            break;
          }
          case 80: {
            Param9 = input.ReadInt64();
            break;
          }
          case 88: {
            Param10 = input.ReadInt64();
            break;
          }
          case 96: {
            Param11 = input.ReadInt64();
            break;
          }
          case 104: {
            Param12 = input.ReadInt64();
            break;
          }
          case 112: {
            Param13 = input.ReadInt64();
            break;
          }
          case 120: {
            Param14 = input.ReadInt64();
            break;
          }
          case 128: {
            Param15 = input.ReadInt64();
            break;
          }
          case 136: {
            Param16 = input.ReadInt64();
            break;
          }
          case 144: {
            Param17 = input.ReadInt64();
            break;
          }
          case 152: {
            Param18 = input.ReadInt64();
            break;
          }
          case 160: {
            Param19 = input.ReadInt64();
            break;
          }
          case 168: {
            Param20 = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class MoveAndPassiveSkillDigitTable : pb::IMessage<MoveAndPassiveSkillDigitTable>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<MoveAndPassiveSkillDigitTable> _parser = new pb::MessageParser<MoveAndPassiveSkillDigitTable>(() => new MoveAndPassiveSkillDigitTable());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<MoveAndPassiveSkillDigitTable> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.MoveAndPassiveSkillDigitReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveAndPassiveSkillDigitTable() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveAndPassiveSkillDigitTable(MoveAndPassiveSkillDigitTable other) : this() {
      entries_ = other.entries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public MoveAndPassiveSkillDigitTable Clone() {
      return new MoveAndPassiveSkillDigitTable(this);
    }

    /// <summary>Field number for the "entries" field.</summary>
    public const int EntriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ReMastersLib.MoveAndPassiveSkillDigit> _repeated_entries_codec
        = pb::FieldCodec.ForMessage(10, global::ReMastersLib.MoveAndPassiveSkillDigit.Parser);
    private readonly pbc::RepeatedField<global::ReMastersLib.MoveAndPassiveSkillDigit> entries_ = new pbc::RepeatedField<global::ReMastersLib.MoveAndPassiveSkillDigit>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ReMastersLib.MoveAndPassiveSkillDigit> Entries {
      get { return entries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as MoveAndPassiveSkillDigitTable);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(MoveAndPassiveSkillDigitTable other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!entries_.Equals(other.entries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= entries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      entries_.WriteTo(output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      entries_.WriteTo(ref output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += entries_.CalculateSize(_repeated_entries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(MoveAndPassiveSkillDigitTable other) {
      if (other == null) {
        return;
      }
      entries_.Add(other.entries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            entries_.AddEntriesFrom(input, _repeated_entries_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            entries_.AddEntriesFrom(ref input, _repeated_entries_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
