// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/TrainerBuildupParameter.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ReMastersLib {

  /// <summary>Holder for reflection information generated from Proto/TrainerBuildupParameter.proto</summary>
  public static partial class TrainerBuildupParameterReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/TrainerBuildupParameter.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static TrainerBuildupParameterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNQcm90by9UcmFpbmVyQnVpbGR1cFBhcmFtZXRlci5wcm90bxIMUmVNYXN0",
            "ZXJzTGliIp0BChdUcmFpbmVyQnVpbGR1cFBhcmFtZXRlchISCgp0cmFpbmVy",
            "X2lkGAEgASgDEiEKGXRyYWluZXJfYnVpbGR1cF9jb25maWdfaWQYAiABKAUS",
            "CgoCaHAYAyABKAUSCwoDYXRrGAQgASgFEgsKA2RlZhgFIAEoBRILCgNzcGEY",
            "BiABKAUSCwoDc3BkGAcgASgFEgsKA3NwZRgIIAEoBSJWChxUcmFpbmVyQnVp",
            "bGR1cFBhcmFtZXRlclRhYmxlEjYKB2VudHJpZXMYASADKAsyJS5SZU1hc3Rl",
            "cnNMaWIuVHJhaW5lckJ1aWxkdXBQYXJhbWV0ZXJiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.TrainerBuildupParameter), global::ReMastersLib.TrainerBuildupParameter.Parser, new[]{ "TrainerId", "TrainerBuildupConfigId", "Hp", "Atk", "Def", "Spa", "Spd", "Spe" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.TrainerBuildupParameterTable), global::ReMastersLib.TrainerBuildupParameterTable.Parser, new[]{ "Entries" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class TrainerBuildupParameter : pb::IMessage<TrainerBuildupParameter>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrainerBuildupParameter> _parser = new pb::MessageParser<TrainerBuildupParameter>(() => new TrainerBuildupParameter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrainerBuildupParameter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.TrainerBuildupParameterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainerBuildupParameter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainerBuildupParameter(TrainerBuildupParameter other) : this() {
      trainerId_ = other.trainerId_;
      trainerBuildupConfigId_ = other.trainerBuildupConfigId_;
      hp_ = other.hp_;
      atk_ = other.atk_;
      def_ = other.def_;
      spa_ = other.spa_;
      spd_ = other.spd_;
      spe_ = other.spe_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainerBuildupParameter Clone() {
      return new TrainerBuildupParameter(this);
    }

    /// <summary>Field number for the "trainer_id" field.</summary>
    public const int TrainerIdFieldNumber = 1;
    private long trainerId_;
    /// <summary>
    /// Trainer.pb
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TrainerId {
      get { return trainerId_; }
      set {
        trainerId_ = value;
      }
    }

    /// <summary>Field number for the "trainer_buildup_config_id" field.</summary>
    public const int TrainerBuildupConfigIdFieldNumber = 2;
    private int trainerBuildupConfigId_;
    /// <summary>
    /// TrainerBuildupConfig.pb
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int TrainerBuildupConfigId {
      get { return trainerBuildupConfigId_; }
      set {
        trainerBuildupConfigId_ = value;
      }
    }

    /// <summary>Field number for the "hp" field.</summary>
    public const int HpFieldNumber = 3;
    private int hp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Hp {
      get { return hp_; }
      set {
        hp_ = value;
      }
    }

    /// <summary>Field number for the "atk" field.</summary>
    public const int AtkFieldNumber = 4;
    private int atk_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Atk {
      get { return atk_; }
      set {
        atk_ = value;
      }
    }

    /// <summary>Field number for the "def" field.</summary>
    public const int DefFieldNumber = 5;
    private int def_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Def {
      get { return def_; }
      set {
        def_ = value;
      }
    }

    /// <summary>Field number for the "spa" field.</summary>
    public const int SpaFieldNumber = 6;
    private int spa_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Spa {
      get { return spa_; }
      set {
        spa_ = value;
      }
    }

    /// <summary>Field number for the "spd" field.</summary>
    public const int SpdFieldNumber = 7;
    private int spd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Spd {
      get { return spd_; }
      set {
        spd_ = value;
      }
    }

    /// <summary>Field number for the "spe" field.</summary>
    public const int SpeFieldNumber = 8;
    private int spe_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int Spe {
      get { return spe_; }
      set {
        spe_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrainerBuildupParameter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrainerBuildupParameter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TrainerId != other.TrainerId) return false;
      if (TrainerBuildupConfigId != other.TrainerBuildupConfigId) return false;
      if (Hp != other.Hp) return false;
      if (Atk != other.Atk) return false;
      if (Def != other.Def) return false;
      if (Spa != other.Spa) return false;
      if (Spd != other.Spd) return false;
      if (Spe != other.Spe) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TrainerId != 0L) hash ^= TrainerId.GetHashCode();
      if (TrainerBuildupConfigId != 0) hash ^= TrainerBuildupConfigId.GetHashCode();
      if (Hp != 0) hash ^= Hp.GetHashCode();
      if (Atk != 0) hash ^= Atk.GetHashCode();
      if (Def != 0) hash ^= Def.GetHashCode();
      if (Spa != 0) hash ^= Spa.GetHashCode();
      if (Spd != 0) hash ^= Spd.GetHashCode();
      if (Spe != 0) hash ^= Spe.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TrainerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(TrainerId);
      }
      if (TrainerBuildupConfigId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TrainerBuildupConfigId);
      }
      if (Hp != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Hp);
      }
      if (Atk != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Atk);
      }
      if (Def != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Def);
      }
      if (Spa != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Spa);
      }
      if (Spd != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Spd);
      }
      if (Spe != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Spe);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TrainerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(TrainerId);
      }
      if (TrainerBuildupConfigId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(TrainerBuildupConfigId);
      }
      if (Hp != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Hp);
      }
      if (Atk != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Atk);
      }
      if (Def != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Def);
      }
      if (Spa != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Spa);
      }
      if (Spd != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Spd);
      }
      if (Spe != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Spe);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TrainerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TrainerId);
      }
      if (TrainerBuildupConfigId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(TrainerBuildupConfigId);
      }
      if (Hp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hp);
      }
      if (Atk != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Atk);
      }
      if (Def != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Def);
      }
      if (Spa != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Spa);
      }
      if (Spd != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Spd);
      }
      if (Spe != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Spe);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrainerBuildupParameter other) {
      if (other == null) {
        return;
      }
      if (other.TrainerId != 0L) {
        TrainerId = other.TrainerId;
      }
      if (other.TrainerBuildupConfigId != 0) {
        TrainerBuildupConfigId = other.TrainerBuildupConfigId;
      }
      if (other.Hp != 0) {
        Hp = other.Hp;
      }
      if (other.Atk != 0) {
        Atk = other.Atk;
      }
      if (other.Def != 0) {
        Def = other.Def;
      }
      if (other.Spa != 0) {
        Spa = other.Spa;
      }
      if (other.Spd != 0) {
        Spd = other.Spd;
      }
      if (other.Spe != 0) {
        Spe = other.Spe;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TrainerId = input.ReadInt64();
            break;
          }
          case 16: {
            TrainerBuildupConfigId = input.ReadInt32();
            break;
          }
          case 24: {
            Hp = input.ReadInt32();
            break;
          }
          case 32: {
            Atk = input.ReadInt32();
            break;
          }
          case 40: {
            Def = input.ReadInt32();
            break;
          }
          case 48: {
            Spa = input.ReadInt32();
            break;
          }
          case 56: {
            Spd = input.ReadInt32();
            break;
          }
          case 64: {
            Spe = input.ReadInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            TrainerId = input.ReadInt64();
            break;
          }
          case 16: {
            TrainerBuildupConfigId = input.ReadInt32();
            break;
          }
          case 24: {
            Hp = input.ReadInt32();
            break;
          }
          case 32: {
            Atk = input.ReadInt32();
            break;
          }
          case 40: {
            Def = input.ReadInt32();
            break;
          }
          case 48: {
            Spa = input.ReadInt32();
            break;
          }
          case 56: {
            Spd = input.ReadInt32();
            break;
          }
          case 64: {
            Spe = input.ReadInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class TrainerBuildupParameterTable : pb::IMessage<TrainerBuildupParameterTable>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TrainerBuildupParameterTable> _parser = new pb::MessageParser<TrainerBuildupParameterTable>(() => new TrainerBuildupParameterTable());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TrainerBuildupParameterTable> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.TrainerBuildupParameterReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainerBuildupParameterTable() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainerBuildupParameterTable(TrainerBuildupParameterTable other) : this() {
      entries_ = other.entries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TrainerBuildupParameterTable Clone() {
      return new TrainerBuildupParameterTable(this);
    }

    /// <summary>Field number for the "entries" field.</summary>
    public const int EntriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ReMastersLib.TrainerBuildupParameter> _repeated_entries_codec
        = pb::FieldCodec.ForMessage(10, global::ReMastersLib.TrainerBuildupParameter.Parser);
    private readonly pbc::RepeatedField<global::ReMastersLib.TrainerBuildupParameter> entries_ = new pbc::RepeatedField<global::ReMastersLib.TrainerBuildupParameter>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ReMastersLib.TrainerBuildupParameter> Entries {
      get { return entries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TrainerBuildupParameterTable);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TrainerBuildupParameterTable other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!entries_.Equals(other.entries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= entries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      entries_.WriteTo(output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      entries_.WriteTo(ref output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      size += entries_.CalculateSize(_repeated_entries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TrainerBuildupParameterTable other) {
      if (other == null) {
        return;
      }
      entries_.Add(other.entries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            entries_.AddEntriesFrom(input, _repeated_entries_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            entries_.AddEntriesFrom(ref input, _repeated_entries_codec);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
