// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/EggUnitHappinessParameter.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ReMastersLib {

  /// <summary>Holder for reflection information generated from Proto/EggUnitHappinessParameter.proto</summary>
  public static partial class EggUnitHappinessParameterReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/EggUnitHappinessParameter.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static EggUnitHappinessParameterReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiVQcm90by9FZ2dVbml0SGFwcGluZXNzUGFyYW1ldGVyLnByb3RvEgxSZU1h",
            "c3RlcnNMaWIijwEKGUVnZ1VuaXRIYXBwaW5lc3NQYXJhbWV0ZXISEgoKdHJh",
            "aW5lcl9pZBgBIAEoAxIRCgloYXBwaW5lc3MYAiABKAUSCgoCaHAYAyABKAUS",
            "CwoDYXRrGAQgASgFEgsKA2RlZhgFIAEoBRILCgNzcGEYBiABKAUSCwoDc3Bk",
            "GAcgASgFEgsKA3NwZRgIIAEoBSJaCh5FZ2dVbml0SGFwcGluZXNzUGFyYW1l",
            "dGVyVGFibGUSOAoHZW50cmllcxgBIAMoCzInLlJlTWFzdGVyc0xpYi5FZ2dV",
            "bml0SGFwcGluZXNzUGFyYW1ldGVyYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.EggUnitHappinessParameter), global::ReMastersLib.EggUnitHappinessParameter.Parser, new[]{ "TrainerId", "Happiness", "Hp", "Atk", "Def", "Spa", "Spd", "Spe" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.EggUnitHappinessParameterTable), global::ReMastersLib.EggUnitHappinessParameterTable.Parser, new[]{ "Entries" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class EggUnitHappinessParameter : pb::IMessage<EggUnitHappinessParameter> {
    private static readonly pb::MessageParser<EggUnitHappinessParameter> _parser = new pb::MessageParser<EggUnitHappinessParameter>(() => new EggUnitHappinessParameter());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EggUnitHappinessParameter> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.EggUnitHappinessParameterReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EggUnitHappinessParameter() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EggUnitHappinessParameter(EggUnitHappinessParameter other) : this() {
      trainerId_ = other.trainerId_;
      happiness_ = other.happiness_;
      hp_ = other.hp_;
      atk_ = other.atk_;
      def_ = other.def_;
      spa_ = other.spa_;
      spd_ = other.spd_;
      spe_ = other.spe_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EggUnitHappinessParameter Clone() {
      return new EggUnitHappinessParameter(this);
    }

    /// <summary>Field number for the "trainer_id" field.</summary>
    public const int TrainerIdFieldNumber = 1;
    private long trainerId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TrainerId {
      get { return trainerId_; }
      set {
        trainerId_ = value;
      }
    }

    /// <summary>Field number for the "happiness" field.</summary>
    public const int HappinessFieldNumber = 2;
    private int happiness_;
    /// <summary>
    /// EggUnitHappinessConfig.pb
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Happiness {
      get { return happiness_; }
      set {
        happiness_ = value;
      }
    }

    /// <summary>Field number for the "hp" field.</summary>
    public const int HpFieldNumber = 3;
    private int hp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Hp {
      get { return hp_; }
      set {
        hp_ = value;
      }
    }

    /// <summary>Field number for the "atk" field.</summary>
    public const int AtkFieldNumber = 4;
    private int atk_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Atk {
      get { return atk_; }
      set {
        atk_ = value;
      }
    }

    /// <summary>Field number for the "def" field.</summary>
    public const int DefFieldNumber = 5;
    private int def_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Def {
      get { return def_; }
      set {
        def_ = value;
      }
    }

    /// <summary>Field number for the "spa" field.</summary>
    public const int SpaFieldNumber = 6;
    private int spa_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Spa {
      get { return spa_; }
      set {
        spa_ = value;
      }
    }

    /// <summary>Field number for the "spd" field.</summary>
    public const int SpdFieldNumber = 7;
    private int spd_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Spd {
      get { return spd_; }
      set {
        spd_ = value;
      }
    }

    /// <summary>Field number for the "spe" field.</summary>
    public const int SpeFieldNumber = 8;
    private int spe_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Spe {
      get { return spe_; }
      set {
        spe_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EggUnitHappinessParameter);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EggUnitHappinessParameter other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TrainerId != other.TrainerId) return false;
      if (Happiness != other.Happiness) return false;
      if (Hp != other.Hp) return false;
      if (Atk != other.Atk) return false;
      if (Def != other.Def) return false;
      if (Spa != other.Spa) return false;
      if (Spd != other.Spd) return false;
      if (Spe != other.Spe) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TrainerId != 0L) hash ^= TrainerId.GetHashCode();
      if (Happiness != 0) hash ^= Happiness.GetHashCode();
      if (Hp != 0) hash ^= Hp.GetHashCode();
      if (Atk != 0) hash ^= Atk.GetHashCode();
      if (Def != 0) hash ^= Def.GetHashCode();
      if (Spa != 0) hash ^= Spa.GetHashCode();
      if (Spd != 0) hash ^= Spd.GetHashCode();
      if (Spe != 0) hash ^= Spe.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TrainerId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(TrainerId);
      }
      if (Happiness != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(Happiness);
      }
      if (Hp != 0) {
        output.WriteRawTag(24);
        output.WriteInt32(Hp);
      }
      if (Atk != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(Atk);
      }
      if (Def != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Def);
      }
      if (Spa != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Spa);
      }
      if (Spd != 0) {
        output.WriteRawTag(56);
        output.WriteInt32(Spd);
      }
      if (Spe != 0) {
        output.WriteRawTag(64);
        output.WriteInt32(Spe);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TrainerId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TrainerId);
      }
      if (Happiness != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Happiness);
      }
      if (Hp != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Hp);
      }
      if (Atk != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Atk);
      }
      if (Def != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Def);
      }
      if (Spa != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Spa);
      }
      if (Spd != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Spd);
      }
      if (Spe != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Spe);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EggUnitHappinessParameter other) {
      if (other == null) {
        return;
      }
      if (other.TrainerId != 0L) {
        TrainerId = other.TrainerId;
      }
      if (other.Happiness != 0) {
        Happiness = other.Happiness;
      }
      if (other.Hp != 0) {
        Hp = other.Hp;
      }
      if (other.Atk != 0) {
        Atk = other.Atk;
      }
      if (other.Def != 0) {
        Def = other.Def;
      }
      if (other.Spa != 0) {
        Spa = other.Spa;
      }
      if (other.Spd != 0) {
        Spd = other.Spd;
      }
      if (other.Spe != 0) {
        Spe = other.Spe;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TrainerId = input.ReadInt64();
            break;
          }
          case 16: {
            Happiness = input.ReadInt32();
            break;
          }
          case 24: {
            Hp = input.ReadInt32();
            break;
          }
          case 32: {
            Atk = input.ReadInt32();
            break;
          }
          case 40: {
            Def = input.ReadInt32();
            break;
          }
          case 48: {
            Spa = input.ReadInt32();
            break;
          }
          case 56: {
            Spd = input.ReadInt32();
            break;
          }
          case 64: {
            Spe = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class EggUnitHappinessParameterTable : pb::IMessage<EggUnitHappinessParameterTable> {
    private static readonly pb::MessageParser<EggUnitHappinessParameterTable> _parser = new pb::MessageParser<EggUnitHappinessParameterTable>(() => new EggUnitHappinessParameterTable());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EggUnitHappinessParameterTable> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.EggUnitHappinessParameterReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EggUnitHappinessParameterTable() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EggUnitHappinessParameterTable(EggUnitHappinessParameterTable other) : this() {
      entries_ = other.entries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EggUnitHappinessParameterTable Clone() {
      return new EggUnitHappinessParameterTable(this);
    }

    /// <summary>Field number for the "entries" field.</summary>
    public const int EntriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ReMastersLib.EggUnitHappinessParameter> _repeated_entries_codec
        = pb::FieldCodec.ForMessage(10, global::ReMastersLib.EggUnitHappinessParameter.Parser);
    private readonly pbc::RepeatedField<global::ReMastersLib.EggUnitHappinessParameter> entries_ = new pbc::RepeatedField<global::ReMastersLib.EggUnitHappinessParameter>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ReMastersLib.EggUnitHappinessParameter> Entries {
      get { return entries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EggUnitHappinessParameterTable);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EggUnitHappinessParameterTable other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!entries_.Equals(other.entries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= entries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      entries_.WriteTo(output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += entries_.CalculateSize(_repeated_entries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EggUnitHappinessParameterTable other) {
      if (other == null) {
        return;
      }
      entries_.Add(other.entries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            entries_.AddEntriesFrom(input, _repeated_entries_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
