// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: Proto/ItemExchangeLinkage.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ReMastersLib {

  /// <summary>Holder for reflection information generated from Proto/ItemExchangeLinkage.proto</summary>
  public static partial class ItemExchangeLinkageReflection {

    #region Descriptor
    /// <summary>File descriptor for Proto/ItemExchangeLinkage.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ItemExchangeLinkageReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9Qcm90by9JdGVtRXhjaGFuZ2VMaW5rYWdlLnByb3RvEgxSZU1hc3RlcnNM",
            "aWIiTQoTSXRlbUV4Y2hhbmdlTGlua2FnZRIeChZpdGVtX2V4Y2hhbmdlX2dy",
            "b3VwX2lkGAEgASgFEhYKDnF1ZXN0X2dyb3VwX2lkGAIgASgFIk4KGEl0ZW1F",
            "eGNoYW5nZUxpbmthZ2VUYWJsZRIyCgdlbnRyaWVzGAEgAygLMiEuUmVNYXN0",
            "ZXJzTGliLkl0ZW1FeGNoYW5nZUxpbmthZ2ViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.ItemExchangeLinkage), global::ReMastersLib.ItemExchangeLinkage.Parser, new[]{ "ItemExchangeGroupId", "QuestGroupId" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ReMastersLib.ItemExchangeLinkageTable), global::ReMastersLib.ItemExchangeLinkageTable.Parser, new[]{ "Entries" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ItemExchangeLinkage : pb::IMessage<ItemExchangeLinkage> {
    private static readonly pb::MessageParser<ItemExchangeLinkage> _parser = new pb::MessageParser<ItemExchangeLinkage>(() => new ItemExchangeLinkage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ItemExchangeLinkage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.ItemExchangeLinkageReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ItemExchangeLinkage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ItemExchangeLinkage(ItemExchangeLinkage other) : this() {
      itemExchangeGroupId_ = other.itemExchangeGroupId_;
      questGroupId_ = other.questGroupId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ItemExchangeLinkage Clone() {
      return new ItemExchangeLinkage(this);
    }

    /// <summary>Field number for the "item_exchange_group_id" field.</summary>
    public const int ItemExchangeGroupIdFieldNumber = 1;
    private int itemExchangeGroupId_;
    /// <summary>
    /// ItemExchangeGroup.pb
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ItemExchangeGroupId {
      get { return itemExchangeGroupId_; }
      set {
        itemExchangeGroupId_ = value;
      }
    }

    /// <summary>Field number for the "quest_group_id" field.</summary>
    public const int QuestGroupIdFieldNumber = 2;
    private int questGroupId_;
    /// <summary>
    /// EventQuestGroup.pb (and more?)
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int QuestGroupId {
      get { return questGroupId_; }
      set {
        questGroupId_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ItemExchangeLinkage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ItemExchangeLinkage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ItemExchangeGroupId != other.ItemExchangeGroupId) return false;
      if (QuestGroupId != other.QuestGroupId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ItemExchangeGroupId != 0) hash ^= ItemExchangeGroupId.GetHashCode();
      if (QuestGroupId != 0) hash ^= QuestGroupId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ItemExchangeGroupId != 0) {
        output.WriteRawTag(8);
        output.WriteInt32(ItemExchangeGroupId);
      }
      if (QuestGroupId != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(QuestGroupId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ItemExchangeGroupId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ItemExchangeGroupId);
      }
      if (QuestGroupId != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(QuestGroupId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ItemExchangeLinkage other) {
      if (other == null) {
        return;
      }
      if (other.ItemExchangeGroupId != 0) {
        ItemExchangeGroupId = other.ItemExchangeGroupId;
      }
      if (other.QuestGroupId != 0) {
        QuestGroupId = other.QuestGroupId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            ItemExchangeGroupId = input.ReadInt32();
            break;
          }
          case 16: {
            QuestGroupId = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class ItemExchangeLinkageTable : pb::IMessage<ItemExchangeLinkageTable> {
    private static readonly pb::MessageParser<ItemExchangeLinkageTable> _parser = new pb::MessageParser<ItemExchangeLinkageTable>(() => new ItemExchangeLinkageTable());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ItemExchangeLinkageTable> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ReMastersLib.ItemExchangeLinkageReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ItemExchangeLinkageTable() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ItemExchangeLinkageTable(ItemExchangeLinkageTable other) : this() {
      entries_ = other.entries_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ItemExchangeLinkageTable Clone() {
      return new ItemExchangeLinkageTable(this);
    }

    /// <summary>Field number for the "entries" field.</summary>
    public const int EntriesFieldNumber = 1;
    private static readonly pb::FieldCodec<global::ReMastersLib.ItemExchangeLinkage> _repeated_entries_codec
        = pb::FieldCodec.ForMessage(10, global::ReMastersLib.ItemExchangeLinkage.Parser);
    private readonly pbc::RepeatedField<global::ReMastersLib.ItemExchangeLinkage> entries_ = new pbc::RepeatedField<global::ReMastersLib.ItemExchangeLinkage>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::ReMastersLib.ItemExchangeLinkage> Entries {
      get { return entries_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ItemExchangeLinkageTable);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ItemExchangeLinkageTable other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!entries_.Equals(other.entries_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= entries_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      entries_.WriteTo(output, _repeated_entries_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += entries_.CalculateSize(_repeated_entries_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ItemExchangeLinkageTable other) {
      if (other == null) {
        return;
      }
      entries_.Add(other.entries_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            entries_.AddEntriesFrom(input, _repeated_entries_codec);
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
